[project]
name = "mcp_llamaindex"
version = "0.1.0"
dependencies = [
    "llama-index",
    "fastmcp>=2.11.3",
]

[project.optional-dependencies]
test = [
    "pytest",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff",
]
